@startuml Issuing a Referral For Analysis
:Start;
:Determine Type of Analysis Needed;
:Prepare Referral Form;
:Provide Referral to Patient;
:Display: "Explain Purpose and Instructions";
:End Process;
:End;
@enduml